### ISSUE TITLE
dependency ntlk install fails with setuptools>=10.0

### ISSUE THREAD

**Issue by JasonBoyles** [rgbkrk/ipython-notebook-cookbook#14]
There's an open issue for ntlk:

https://github.com/nltk/nltk/issues/824

Looks like the only workaround is to use setuptools<10.0

If we drop the ntlk requirement, what does that cost us?

I'm able to install ipython[notebook]==2.2.0 without it, it seems.

Guessing the ntlk 3.0.1 release will fix this, but no ETA.

**Comment by rgbkrk** [comment]
Thanks for reporting this. nltk should be standalone, perhaps we'll just drop it for now unless someone complains.

Thanks for your stalwart dedication to the cookbook and orchestration templates. Mind if I add you as a collaborator @JasonBoyles?

**Comment by rgbkrk** [comment]
Went ahead and dropped nltk in 459d7de3974b7cb31d636d2e7b6f9935d88338ca. Pretty annoying that setuptools introduced backwards incompatible changes meaning our pinned dependency of nltk was useless.

**Comment by JasonBoyles** [comment]
You're welcome! Sure you can add me as a contributor! I'd be happy to help!
