### ISSUE TITLE
Possible to pin versions installed via extra_packages?

### ISSUE THREAD

**Issue by davidski** [rgbkrk/ipython-notebook-cookbook#20]
Is it possible to use `extra_packages` to install specific versions of packages into the ipython virtualenv? I was recently bit when a fresh environment I spun up grabbed a newer version of a client lib with different behavior. I'd like to ensure that I'm getting specific versions in the ipython virtual env.

**Comment by rgbkrk** [comment]
You sure can. It gets installed via pip, the same way the `:scientific_stack` list is setup.

To be honest, I definitely don't use this cookbook anymore (even though I know that a handful of folks are). I'm open to pull requests to help bring this forward as I would probably not setup a system in this way anymore (this was overreaching).

**Comment by davidski** [comment]
Thanks for the quick response! I didn't realize the python_pip resource didn't require a separate `version` property and would instead respect the `foo==1.2.3` syntax. Doh!

Thanks for your contributions in creating this cookbook. It does the job for my current needs. :)
